import os
import django

# Set the DJANGO_SETTINGS_MODULE environment variable
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'EXAMSEATINGAUTOGENERATEDSYSTEM.settings')

# Ensure Django is properly initialized
django.setup()

from adminapp.models import Room

room_data = [
    {'room_number': '103'},
    {'room_number': '104'},
    {'room_number': '105'},
    {'room_number': '106'},
    {'room_number': '110'},
    {'room_number': '111'},
    {'room_number': '112'},
    {'room_number': '113'},
    {'room_number': '116'},
    {'room_number': '117'},
    {'room_number': '118'},
    {'room_number': '119'},
    # Add more room numbers as needed
]

for data in room_data:
    room = Room(**data)
    room.save()
