# Generated by Django 4.2.2 on 2024-01-04 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AddexamHall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(null=True)),
                ("starttime", models.TimeField(null=True)),
                ("endtime", models.TimeField(null=True)),
                ("department", models.CharField(max_length=10, null=True)),
                ("year", models.CharField(max_length=10, null=True)),
                ("noofrooms", models.PositiveIntegerField(null=True)),
                ("noofbenches", models.PositiveIntegerField(null=True)),
                ("seats_per_bench", models.PositiveIntegerField(null=True)),
                ("total_benches", models.PositiveIntegerField(null=True)),
                ("total_seats", models.PositiveIntegerField(null=True)),
            ],
            options={
                "db_table": "AddexamHall",
            },
        ),
        migrations.CreateModel(
            name="AddFaculty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=10, null=True)),
                ("email", models.EmailField(max_length=10, null=True)),
                ("contact", models.CharField(max_length=10, null=True)),
                ("branch", models.CharField(max_length=10, null=True)),
                ("subject", models.CharField(max_length=10, null=True)),
                ("semester", models.CharField(max_length=10, null=True)),
                ("year", models.CharField(max_length=10, null=True)),
                ("image", models.FileField(upload_to="static\\faculty")),
                ("profilename", models.CharField(max_length=50, null=True)),
                ("password", models.CharField(max_length=20, null=True)),
            ],
            options={
                "db_table": "Addfaculty",
            },
        ),
        migrations.CreateModel(
            name="AddStudent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rollnumber", models.CharField(max_length=50, null=True)),
                ("name", models.CharField(max_length=50, null=True)),
                ("email", models.EmailField(max_length=254, null=True)),
                ("contact", models.CharField(max_length=50, null=True)),
                ("branch", models.CharField(max_length=50, null=True)),
                ("semester", models.CharField(max_length=50, null=True)),
                ("year", models.CharField(max_length=20, null=True)),
                ("profile", models.FileField(upload_to="static\\profiles")),
                ("profilename", models.CharField(max_length=50, null=True)),
                ("RoomNo", models.CharField(max_length=20, null=True)),
                ("BenchNo", models.CharField(max_length=20, null=True)),
                ("SeatNumber", models.CharField(max_length=20, null=True)),
                ("password", models.CharField(max_length=20, null=True)),
            ],
            options={
                "db_table": "AddStudent",
            },
        ),
        migrations.CreateModel(
            name="AddTimeTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("classone", models.CharField(max_length=20, null=True)),
                ("classtwo", models.CharField(max_length=20, null=True)),
                ("classthree", models.CharField(max_length=20, null=True)),
                ("classfour", models.CharField(max_length=20, null=True)),
                ("classfive", models.CharField(max_length=20, null=True)),
                ("classsix", models.CharField(max_length=20, null=True)),
                ("classseven", models.CharField(max_length=20, null=True)),
                ("classeight", models.CharField(max_length=20, null=True)),
                ("facultyemail", models.EmailField(max_length=254, null=True)),
            ],
            options={
                "db_table": "Timetable",
            },
        ),
        migrations.CreateModel(
            name="AdminAnnounce",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("announcement", models.TextField(null=True)),
                ("senderemail", models.EmailField(max_length=254, null=True)),
            ],
            options={
                "db_table": "Announcement",
            },
        ),
        migrations.CreateModel(
            name="Examallotment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Branch", models.CharField(max_length=20, null=True)),
                ("RoomNo", models.CharField(max_length=20, null=True)),
                ("BenchNo", models.CharField(max_length=20, null=True)),
                ("SeatNumber", models.CharField(max_length=20, null=True)),
                (
                    "Student_Email",
                    models.EmailField(default="pending", max_length=254, null=True),
                ),
                ("Student_Id", models.CharField(max_length=20, null=True)),
                ("date", models.DateField(null=True)),
                ("starttime", models.TimeField(null=True)),
                ("endtime", models.TimeField(null=True)),
            ],
            options={
                "db_table": "Examallotment",
            },
        ),
        migrations.CreateModel(
            name="Invigilation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("branch", models.CharField(max_length=50, null=True)),
                ("roomno", models.CharField(max_length=50, null=True)),
                ("faculty_email", models.EmailField(max_length=254, null=True)),
                ("date", models.CharField(max_length=50, null=True)),
                ("start_time", models.CharField(max_length=50, null=True)),
                ("end_time", models.CharField(max_length=50, null=True)),
            ],
            options={
                "db_table": "Invigilation",
            },
        ),
    ]
