# Generated by Django 5.0.2 on 2024-03-28 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addexamhall',
            name='department',
        ),
        migrations.RemoveField(
            model_name='addexamhall',
            name='year',
        ),
    ]
