# Generated by Django 5.0.2 on 2024-03-28 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_remove_addexamhall_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addexamhall',
            name='seats_per_bench',
        ),
    ]
