# Generated by Django 5.0.2 on 2024-03-28 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_remove_addexamhall_seats_per_bench'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=20)),
                ('bench_number', models.CharField(max_length=20)),
                ('seat_number', models.CharField(max_length=20)),
                ('exam_hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.addexamhall')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.addstudent')),
            ],
            options={
                'db_table': 'SeatAllocation',
            },
        ),
    ]
