# Generated by Django 5.0.2 on 2024-03-28 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_alter_addtimetable_classeight_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvigilationAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_name', models.CharField(max_length=100)),
                ('exam_room', models.CharField(max_length=20)),
                ('exam_date', models.DateField()),
                ('exam_start_time', models.TimeField()),
                ('exam_end_time', models.TimeField()),
            ],
            options={
                'db_table': 'InvigilationAssignment',
            },
        ),
    ]
