# Generated by Django 5.0.3 on 2024-03-29 08:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_invigilationassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminannounce',
            name='annuncementdate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
