# Generated by Django 5.0.3 on 2024-03-29 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_adminannounce_annuncementdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addtimetable',
            name='classeight',
        ),
        migrations.RemoveField(
            model_name='addtimetable',
            name='classfive',
        ),
        migrations.RemoveField(
            model_name='addtimetable',
            name='classfour',
        ),
        migrations.RemoveField(
            model_name='addtimetable',
            name='classone',
        ),
        migrations.RemoveField(
            model_name='addtimetable',
            name='classseven',
        ),
        migrations.RemoveField(
            model_name='addtimetable',
            name='classsix',
        ),
        migrations.RemoveField(
            model_name='addtimetable',
            name='classthree',
        ),
        migrations.RemoveField(
            model_name='addtimetable',
            name='classtwo',
        ),
        migrations.RemoveField(
            model_name='addtimetable',
            name='facultyemail',
        ),
        migrations.AddField(
            model_name='addtimetable',
            name='days_per_week',
            field=models.IntegerField(default=6),
        ),
        migrations.AddField(
            model_name='addtimetable',
            name='insert_break_after_period',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='addtimetable',
            name='number_of_batches',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='addtimetable',
            name='number_of_teachers',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='addtimetable',
            name='slots_per_day',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterModelTable(
            name='addtimetable',
            table=None,
        ),
    ]
