# Generated by Django 5.0.3 on 2024-03-30 00:08

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_remove_addtimetable_classeight_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='addtimetable',
            name='days_per_week',
        ),
        migrations.RemoveField(
            model_name='addtimetable',
            name='insert_break_after_period',
        ),
        migrations.RemoveField(
            model_name='addtimetable',
            name='number_of_batches',
        ),
        migrations.RemoveField(
            model_name='addtimetable',
            name='number_of_teachers',
        ),
        migrations.RemoveField(
            model_name='addtimetable',
            name='slots_per_day',
        ),
        migrations.AddField(
            model_name='addtimetable',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], default=6, max_length=10),
        ),
        migrations.AddField(
            model_name='addtimetable',
            name='end_time',
            field=models.TimeField(default=datetime.time(5, 38, 35, 800840)),
        ),
        migrations.AddField(
            model_name='addtimetable',
            name='start_time',
            field=models.TimeField(default=datetime.time(5, 38, 35, 800840)),
        ),
        migrations.AddField(
            model_name='addtimetable',
            name='subject',
            field=models.CharField(default='Java', max_length=100),
        ),
        migrations.AlterModelTable(
            name='addtimetable',
            table='AddTimeTable',
        ),
        migrations.AddField(
            model_name='addtimetable',
            name='batch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adminapp.batch'),
        ),
        migrations.AddField(
            model_name='addtimetable',
            name='teacher',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='adminapp.teacher'),
        ),
    ]
