# Generated by Django 5.0.3 on 2024-03-30 00:09

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0009_batch_teacher_remove_addtimetable_days_per_week_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtimetable',
            name='end_time',
            field=models.TimeField(default=datetime.time(5, 39, 52, 106009)),
        ),
        migrations.AlterField(
            model_name='addtimetable',
            name='start_time',
            field=models.TimeField(default=datetime.time(5, 39, 52, 106009)),
        ),
        migrations.AlterField(
            model_name='addtimetable',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adminapp.teacher'),
        ),
    ]
