# Generated by Django 5.0.3 on 2024-03-30 00:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0010_alter_addtimetable_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtimetable',
            name='end_time',
            field=models.TimeField(default=datetime.time(5, 41, 41, 754663)),
        ),
        migrations.AlterField(
            model_name='addtimetable',
            name='start_time',
            field=models.TimeField(default=datetime.time(5, 41, 41, 754663)),
        ),
    ]
