# Generated by Django 5.0.3 on 2024-03-30 00:18

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0012_alter_addtimetable_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtimetable',
            name='end_time',
            field=models.TimeField(default=datetime.time(5, 48, 36, 767558)),
        ),
        migrations.AlterField(
            model_name='addtimetable',
            name='start_time',
            field=models.TimeField(default=datetime.time(5, 48, 36, 767558)),
        ),
        migrations.AlterField(
            model_name='addtimetable',
            name='teacher',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='adminapp.teacher'),
        ),
    ]
