# Generated by Django 5.0.3 on 2024-03-30 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0013_alter_addtimetable_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtimetable',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.batch'),
        ),
        migrations.AlterField(
            model_name='addtimetable',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], default='Monday', max_length=10),
        ),
        migrations.AlterField(
            model_name='addtimetable',
            name='end_time',
            field=models.TimeField(default='03:30'),
        ),
        migrations.AlterField(
            model_name='addtimetable',
            name='start_time',
            field=models.TimeField(default='09:30'),
        ),
        migrations.AlterField(
            model_name='addtimetable',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.teacher'),
        ),
    ]
