# Generated by Django 5.0.3 on 2024-03-30 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0015_alter_addtimetable_end_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addtimetable',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='addtimetable',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='Batch',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
