# Generated by Django 5.0.3 on 2024-03-30 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0017_addtimetable_batch_addtimetable_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addtimetable',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='addtimetable',
            name='start_time',
        ),
        migrations.AddField(
            model_name='addtimetable',
            name='period',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='addtimetable',
            name='batch',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='addtimetable',
            name='day',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='addtimetable',
            name='subject',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='addtimetable',
            name='teacher',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterModelTable(
            name='addtimetable',
            table=None,
        ),
    ]
