# Generated by Django 5.0.3 on 2024-03-30 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0018_remove_addtimetable_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtimetable',
            name='period',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='1', max_length=1),
        ),
        migrations.AlterModelTable(
            name='addtimetable',
            table='AddTimeTable',
        ),
    ]
