# Generated by Django 5.0.3 on 2024-03-30 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0019_alter_addtimetable_period_alter_addtimetable_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addtimetable',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='addtimetable',
            name='day',
        ),
        migrations.RemoveField(
            model_name='addtimetable',
            name='period',
        ),
        migrations.RemoveField(
            model_name='addtimetable',
            name='teacher',
        ),
        migrations.AddField(
            model_name='addtimetable',
            name='iv_cse_a_faculty',
            field=models.CharField(default='Prabhakara Rao', max_length=100, verbose_name='IV CSE A Faculty'),
        ),
        migrations.AddField(
            model_name='addtimetable',
            name='iv_cse_b_faculty',
            field=models.CharField(default='Akhila', max_length=100, verbose_name='IV CSE B Faculty'),
        ),
        migrations.AddField(
            model_name='addtimetable',
            name='iv_cse_c_faculty',
            field=models.CharField(default='SriLatha', max_length=100, verbose_name='IV CSE C Faculty'),
        ),
    ]
