# Generated by Django 5.0.3 on 2024-03-31 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0020_remove_addtimetable_batch_remove_addtimetable_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtimetable',
            name='iv_cse_a_faculty',
            field=models.CharField(default='Prabhakara Rao', max_length=100, verbose_name='CSE A Faculty'),
        ),
        migrations.AlterField(
            model_name='addtimetable',
            name='iv_cse_b_faculty',
            field=models.CharField(default='Akhila', max_length=100, verbose_name='CSE B Faculty'),
        ),
        migrations.AlterField(
            model_name='addtimetable',
            name='iv_cse_c_faculty',
            field=models.CharField(default='SriLatha', max_length=100, verbose_name='CSE C Faculty'),
        ),
    ]
