# Generated by Django 5.0.3 on 2024-04-01 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0022_delete_invigilation_delete_invigilationassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addfaculty',
            name='email',
            field=models.EmailField(max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='addstudent',
            name='rollnumber',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
