# Generated by Django 5.0.3 on 2024-04-01 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0023_alter_addfaculty_email_alter_addstudent_rollnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addfaculty',
            name='email',
            field=models.EmailField(max_length=10, null=True),
        ),
    ]
