# Generated by Django 5.0.3 on 2024-04-02 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0024_alter_addfaculty_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addstudent',
            name='BenchNo',
        ),
        migrations.RemoveField(
            model_name='addstudent',
            name='RoomNo',
        ),
        migrations.RemoveField(
            model_name='addstudent',
            name='SeatNumber',
        ),
        migrations.RemoveField(
            model_name='addstudent',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='addstudent',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='addstudent',
            name='email',
        ),
        migrations.RemoveField(
            model_name='addstudent',
            name='password',
        ),
        migrations.RemoveField(
            model_name='addstudent',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='addstudent',
            name='profilename',
        ),
        migrations.RemoveField(
            model_name='addstudent',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='addstudent',
            name='year',
        ),
    ]
