# Generated by Django 5.0.3 on 2024-04-02 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0025_remove_addstudent_benchno_remove_addstudent_roomno_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examallotment',
            name='Branch',
        ),
        migrations.RemoveField(
            model_name='examallotment',
            name='Student_Email',
        ),
    ]
