# Generated by Django 5.0.3 on 2024-04-19 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0026_remove_examallotment_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addexamhall',
            name='rooms_list',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='addexamhall',
            name='students_per_bench',
            field=models.IntegerField(choices=[(2, 'Two students per bench'), (3, 'Three students per bench')], null=True),
        ),
    ]
