# Generated by Django 5.0.3 on 2024-04-19 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0028_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addexamhall',
            name='students_per_bench',
        ),
    ]
