# Generated by Django 5.0.3 on 2024-04-20 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0029_remove_addexamhall_students_per_bench'),
    ]

    operations = [
        migrations.AddField(
            model_name='addexamhall',
            name='students_per_bench',
            field=models.IntegerField(choices=[(2, 'Two students per bench'), (3, 'Three students per bench')], null=True),
        ),
    ]
