# Generated by Django 5.0.3 on 2024-04-20 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0030_addexamhall_students_per_bench'),
    ]

    operations = [
        migrations.AddField(
            model_name='addstudent',
            name='department',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
