# Generated by Django 5.0.3 on 2024-04-20 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0031_addstudent_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='examallotment',
            name='department',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
