# Generated by Django 5.0.3 on 2024-04-22 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0032_examallotment_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='addstudent',
            name='contact',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='addstudent',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='addstudent',
            name='profile_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='addstudent',
            name='semester',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='addstudent',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
