# Generated by Django 5.0.3 on 2024-04-22 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0033_addstudent_contact_addstudent_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addstudent',
            name='contact',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
