# Generated by Django 5.0.3 on 2024-04-22 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0034_alter_addstudent_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='addstudent',
            name='password',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
