# Generated by Django 5.0.3 on 2024-04-25 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0035_addstudent_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SeatAllocation',
        ),
    ]
